# **IBM Data Science Capstone Six - Folium Mapping**

In [143]:
import folium
import pandas as pd
import requests

In [144]:
# Import folium MarkerCluster plugin
from folium.plugins import MarkerCluster

# Import folium MousePosition plugin
from folium.plugins import MousePosition

# Import folium DivIcon plugin
from folium.features import DivIcon

In [145]:
# Download and read the `spacex_launch_geo.csv`
# from js import fetch (Generates 'ModuleNotFoundError' in Jupyter, js not available)

import io

---

### Task 1: Mark all launch sites on a map

In [148]:
URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv'

spacex_df = pd.read_csv(URL)

# Code modified from lesson

In [149]:
spacex_df.head()

,Flight Number,Date,Time (UTC),Booster Version,Launch Site,Payload,Payload Mass (kg),Orbit,Customer,Landing Outcome,class,Lat,Long
0,1,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0.0,LEO,SpaceX,Failure (parachute),0,28.562302,-80.577356
1,2,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel o...",0.0,LEO (ISS),NASA (COTS) NRO,Failure (parachute),0,28.562302,-80.577356
2,3,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2+,525.0,LEO (ISS),NASA (COTS),No attempt,0,28.562302,-80.577356
3,4,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500.0,LEO (ISS),NASA (CRS),No attempt,0,28.562302,-80.577356
4,5,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677.0,LEO (ISS),NASA (CRS),No attempt,0,28.562302,-80.577356

In [150]:
# Select relevant sub-columns: `Launch Site`, `Lat(Latitude)`, `Long(Longitude)`, `class`

spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class', ]]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

In [151]:
# Pin Launch Sites to a map
    # Start location (i.e. nasa_coordinate) is NASA Johnson Space Center

nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

In [152]:
# Create a circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle = folium.Circle(nasa_coordinate, radius=1000, color='black', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))

# Create a circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:blue;"><b>%s</b></div>' % 'NASA JSC'
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

In [153]:
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

### Create folium circles and markers for each launch site in the data frame 'launch_sites_df'

In [155]:
# Map initialization
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)

In [156]:
# Launch Site CCAFS LC-40
CCAFS_LC40_coordinate = [28.562302, -80.577356]

circle_CCAFS_LC40 = folium.Circle(
    CCAFS_LC40_coordinate,
    radius=1000, color='black',
    fill=True).add_child(folium.Popup('CCAFS LC-40'))

marker_CCAFS_LC40 = folium.map.Marker(
    CCAFS_LC40_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'CCAFS LC-40',
        )
    )

site_map.add_child(circle_CCAFS_LC40)
site_map.add_child(marker_CCAFS_LC40)


# Launch Site CCAFS SLC-40
CCAFS_SLC40_coordinate = [28.563197,-80.576820]

circle_CCAFS_SLC40 = folium.Circle(
    CCAFS_SLC40_coordinate,
    radius=1000, color='black',
    fill=True).add_child(folium.Popup('CCAFS SLC-40'))

marker_CCAFS_SLC40 = folium.map.Marker(
    CCAFS_SLC40_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'CCAFS SLC-40',
        )
    )

site_map.add_child(circle_CCAFS_SLC40)
site_map.add_child(marker_CCAFS_SLC40)


# Launch Site KSC LC-39A
KSC_LC39A_coordinate = [28.573255,-80.646895]

circle_KSC_LC39A = folium.Circle(
    KSC_LC39A_coordinate,
    radius=1000, color='black',
    fill=True).add_child(folium.Popup('KSC LC3-9A'))
marker_KSC_LC39A = folium.map.Marker(
    KSC_LC39A_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'KSC LC-39A',
        )
    )

site_map.add_child(circle_KSC_LC39A)
site_map.add_child(marker_KSC_LC39A)


# Launch Site VAFB LC-4E
VAFB_SLC4E_coordinate = [34.632834,-120.610745]

circle_VAFB_SLC4E = folium.Circle(
    VAFB_SLC4E_coordinate,
    radius=1000, color='black',
    fill=True).add_child(folium.Popup('VAFB SLC-4E'))

marker_VAFB_SLC4E = folium.map.Marker(
    VAFB_SLC4E_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'VAFB LC-4E',
        )
    )

site_map.add_child(circle_VAFB_SLC4E)
site_map.add_child(marker_VAFB_SLC4E)

### Task 2: Mark the success/failed launches for each site on the map

Add the launch outcomes for each site, determine which sites have high success rates. The data frame spacex_df class column indicates if a launch was successful or not

In [158]:
spacex_df.tail(10)

     Launch Site        Lat       Long  class
46    KSC LC-39A  28.573255 -80.646895      1
47    KSC LC-39A  28.573255 -80.646895      1
48    KSC LC-39A  28.573255 -80.646895      1
49  CCAFS SLC-40  28.563197 -80.576820      1
50  CCAFS SLC-40  28.563197 -80.576820      1
51  CCAFS SLC-40  28.563197 -80.576820      0
52  CCAFS SLC-40  28.563197 -80.576820      0
53  CCAFS SLC-40  28.563197 -80.576820      0
54  CCAFS SLC-40  28.563197 -80.576820      1
55  CCAFS SLC-40  28.563197 -80.576820      0

Note:  A launch only happens in one of four launch sites. Many launch records will have the same coordinate. Use `MarkerCluster` to simplify a map containing many markers having the same coordinates.

In [160]:
marker_cluster = MarkerCluster()

In [161]:
# Create a new column in 'spacex_df' dataframe called 'marker_color'
# Store the marker colors based on the 'class' value

# Class = 1 = Success = Green
# Class = 0 = Fail = Red

# Function to assign color to launch outcome
def mark_color(launch):
    if launch == 1:
        return 'green'
    else:
        return 'red'
    
spacex_df['marker_color'] = spacex_df['class'].apply(mark_color)
spacex_df.tail(10)

     Launch Site        Lat       Long  class marker_color
46    KSC LC-39A  28.573255 -80.646895      1        green
47    KSC LC-39A  28.573255 -80.646895      1        green
48    KSC LC-39A  28.573255 -80.646895      1        green
49  CCAFS SLC-40  28.563197 -80.576820      1        green
50  CCAFS SLC-40  28.563197 -80.576820      1        green
51  CCAFS SLC-40  28.563197 -80.576820      0          red
52  CCAFS SLC-40  28.563197 -80.576820      0          red
53  CCAFS SLC-40  28.563197 -80.576820      0          red
54  CCAFS SLC-40  28.563197 -80.576820      1        green
55  CCAFS SLC-40  28.563197 -80.576820      0          red

In [172]:
spacex_df.tail(10)

     Launch Site        Lat       Long  class marker_color
46    KSC LC-39A  28.573255 -80.646895      1        green
47    KSC LC-39A  28.573255 -80.646895      1        green
48    KSC LC-39A  28.573255 -80.646895      1        green
49  CCAFS SLC-40  28.563197 -80.576820      1        green
50  CCAFS SLC-40  28.563197 -80.576820      1        green
51  CCAFS SLC-40  28.563197 -80.576820      0          red
52  CCAFS SLC-40  28.563197 -80.576820      0          red
53  CCAFS SLC-40  28.563197 -80.576820      0          red
54  CCAFS SLC-40  28.563197 -80.576820      1        green
55  CCAFS SLC-40  28.563197 -80.576820      0          red

In [184]:
site_map.add_child(marker_cluster)

spacex_df['map_coord'] = spacex_df.apply(lambda x: [x['Lat'], x['Long']], axis = 1)

for index, record in spacex_df.iterrows():
    marker = folium.Marker(
        location = spacex_df['map_coord'][index],
        icon = folium.Icon(color='white'),
        icon_color = spacex_df['marker_color'][index]).add_to(marker_cluster)
    
marker_cluster.add_child(marker)

site_map

### TASK 3: Calculate the distances between a launch site to its proximities

In [189]:
# Task 3a. Add "MousePosition" on the map to get a coordinate [ Given in lesson ]

# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position = 'topright',
    separator = ' Long: ',
    empty_string = 'NaN',
    lng_first = False,
    num_digits = 20,
    prefix = 'Lat:',
    lat_formatter = formatter,
    lng_formatter = formatter,
)

site_map.add_child(mouse_position)
site_map

In [196]:


from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

In [208]:
        # Florida
# Atl Ocean Posit (~CPA): Lat: 28.55859, Long: -80.55652
atl_ocean_lat = 28.55859
atl_ocean_lon = -80.55652

# East Runway Terminus Posit: Lat: 28.59455, Long: -806811
# Intersecton Posit: Lat: 28.56266, Long: -8060929

        # Cali
# Pac Ocean Posit (~CPA): Lat: 34.6373 , Long: -120.62439
pac_ocean_lat = 34.6373
pac_ocean_lon = -120.62439

# Vandenberg Runway Terminus Posit: Lat: 34.74223 , Long: -120.56714
# Lompoc Airport (Graphic): Lat: 34.66569, Long: -120.46715

# Launch Sites:
CCAFS_LC40_lat = 28.562302
CCAFS_LC40_lon = -80.577356

CCAFS_SLC40_lat = 28.563197
CCAFS_SLC40_lon = -80.576820

KSC_LC39A_lat = 28.573255
KSC_LC39A_lon = -80.646895

VAFB_SLC4E_lat = 34.632834
VAFB_SLC4E_lon = -120.610745

In [204]:
# Pick the closest coastline point and calculate the distance between the coastline point and the launch site.
   # distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)

In [222]:
# Space East

distance_coastline_east = calculate_distance(CCAFS_SLC40_lat, CCAFS_SLC40_long, atl_ocean_lat, atl_ocean_lon)
print(distance_coastline_east, 'km')

2.0483270071925523 km

In [218]:
# Draw a `PolyLine` between a launch site to the selected coastline point

florida_locations = [
    [28.55859,-80.55652], # Atl Ocean Posit
    [28.563197,-80.576820], # CAFS SLC-40
]

california_locations = [
    [34.6373,-120.62439], # Pac Ocean Posit
    [34.632834,-120.610745], # VAFB SLC-4E
]

fl_dist_line = folium.PolyLine(florida_locations, weight=2)
# cali_dist_line = folium.PolyLine(california_locations, weight=2)

site_map.add_child(dist_line)